name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-api:
    name: Lint & API Smoke Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the app in the background (Mock Mode because OPENAI_API_KEY is not set)
      - name: Start FastAPI (background)
        run: |
          python -m uvicorn app:app --host 127.0.0.1 --port 8000 --workers 1 &
          echo $! > uvicorn.pid
          sleep 4

      - name: Hit /docs to verify server is up
        run: |
          curl -f http://127.0.0.1:8000/docs

      - name: Hit /ask with a sample payload
        run: |
          curl -f -X POST http://127.0.0.1:8000/ask \
               -H "Content-Type: application/json" \
               -d '{"message":"How do I reset my password?"}'

      - name: Stop FastAPI
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then kill $(cat uvicorn.pid) || true; fi

  build-docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: supportbot-api:ci
